### ISSUE TITLE
Drop nsq-lookup module?

### ISSUE THREAD

**Issue by makara** [Wiredcraft/nsq-strategies#10]
Their recent changes are too random with the behaviors changing randomly and no tags, no tests, no changelogs etc. See https://github.com/segmentio/nsq-lookup/commits/master.

I don't think they are maintaining it properly and I wouldn't bother argue about that with them, but simply drop the module and implement something with this module itself, but up to you @xavierchow .

**Comment by xavierchow** [comment]
I don't have time to rewrite the lookup recently, we can stick to 1.0.2 as a short term solution.

**Comment by makara** [comment]
No problem. I'm half way there already but yeah we use the old version for now.

**Comment by xavierchow** [comment]
using APIs instead, closing
