### ISSUE TITLE
Nsq major version(1.0.0) released

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/nsq-strategies#12]
https://github.com/nsqio/nsq/releases/tag/v1.0.0-compat
A major version was released 4 days ago with incompatible interface, so the current nsq-strategies is not working with v1.0.0(root cause is addressed in [nsqlookup](https://github.com/segmentio/nsq-lookup/blob/master/index.js#L58), there's no `data` in body anymore)

Please stick to the olde stable nsq version(v0.3.8) temporarily, if you're with docker, use tag as `nsqio/nsq:v0.3.8`.
We are gonna apply an upgrade soon(probably with https://github.com/Wiredcraft/nsq-strategies/issues/10)

@zbal  @sunsongxp @makara @wwayne @haishanh @ChopperLee2011 @CCharlieLi

**Comment by makara** [comment]
Yeah let me finish #10.

**Comment by xavierchow** [comment]
@makara Do you need help with #10?

**Comment by makara** [comment]
Not really, just need some time.

**Comment by xavierchow** [comment]
@makara it's been staled for 2 years and it's blocking omni, ppl are building separated logic for different Omni components instead of using this npm.
can you help to find somebody on it?

**Comment by zbal** [comment]
local implementation example:

- https://github.com/Wiredcraft/omni-oms/pull/58/files#diff-1c5bbe112749c4a2a317036511dc48ec

**Comment by pivstone** [comment]
DMP custom:  https://github.com/Wiredcraft/omni-dmp/tree/master/server/lib/nsq
omni-gifting: https://github.com/Wiredcraft/omni-gifting/tree/master/server/lib/nsq

**Comment by woodpig07** [comment]
I've spent some time on checking latest code, it looks all the incompatible parts (mostly deprecated nsqd HTTP endpoints)were covered after v0.1.4
https://github.com/Wiredcraft/nsq-strategies/compare/v0.1.4...v0.2.1

Run test cases on nsq v1.1.0 look all ok
https://github.com/Wiredcraft/nsq-strategies/pull/19

@pivstone is there other incompatibilities I don't know?

**Comment by pivstone** [comment]
> I've spent some time on checking latest code, it looks all the incompatible parts (mostly deprecated nsqd HTTP endpoints)were covered after v0.1.4
> [v0.1.4...v0.2.1](https://github.com/Wiredcraft/nsq-strategies/compare/v0.1.4...v0.2.1)
> 
> Run test cases on nsq v1.1.0 look all ok
> #19
> 
> @pivstone is there other incompatibilities I don't know?

No idea from my side. I've been told don't use `nsq-strategies` before I implemented DMP because of incompatible issue.

**Comment by CCharlieLi** [comment]
nsq-strategies has been upgraded to use nsqjs 0.12.1, closing.
