### ISSUE TITLE
Reject might be called multiple times

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/nsq-strategies#15]
https://github.com/Wiredcraft/nsq-strategies/blob/master/lib/Producer.js#L53,
Please help to check if it creates an issue. @pivstone

**Comment by xavierchow** [comment]
There was a critical issue(async callback twice) in the old tag, https://github.com/Wiredcraft/nsq-strategies/blob/v0.1.2/lib/producer.js#L59.

**Comment by pivstone** [comment]
Do we have any test code to reproduce the scenario?

**Comment by xavierchow** [comment]
Not yet, you can help to create a test case.

**Comment by pivstone** [comment]
for v0.1.2:  https://runkit.com/pivstone/5b30959b563c56001546c7c6  
for master:  https://runkit.com/pivstone/5b2b23f7b5515f0012c30e45

 But I can't reproduce the case.

**Comment by pivstone** [comment]
Sorry, I can't reproduce the issue.  The test case is [here](https://github.com/Wiredcraft/nsq-strategies/blob/reproduce_issue/test/producer.test.js#L409) . The branch is based on the tag v 1.2.0

**Comment by xavierchow** [comment]
You didn't use the lookupd, https://github.com/Wiredcraft/nsq-strategies/blob/reproduce_issue/lib/producer.js#L32 so it won't hit the `async.each`.

**Comment by xavierchow** [comment]
I verified with an example,

https://gist.github.com/xavierchow/2c99faa37a8d1d5f3e1424891b8a9517#file-promiserejecttwice-js


https://github.com/Wiredcraft/api-boilerplate/blob/0fa9471576fbd5a54b50ed6055de36ffe1507d3d/server/lib/loggers/debug.js#L1-L13

**Comment by pivstone** [comment]
The Callback simulation is here. https://runkit.com/pivstone/5b3c8afa3b535b00120f0858.
The error callback only calls once. Maybe something wrong?

**Comment by xavierchow** [comment]
You didn't use aysnc, so even the callback has been called twice there is no error thrown.

**Comment by xavierchow** [comment]
closing as it has switched to async/await in place of callback and `async.js`
